version: 2
general:
  branches:
    only:
      - master
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - setup_remote_docker:
          version: 20.10.14
      - checkout
      - run:
          name: Deploy
          command: |
            sudo apt update -y
            sudo apt install awscli -y
            echo Start deploy for S3
            curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
            sudo apt-get install nodejs
            npm i
            npm run build
            aws s3 sync build s3://sonish-bucket 
            echo Deploy end
workflows:
  version: 2
  deploy_ec2:
    jobs:
      - build
