version: 2
general:
  branches:
    only:
      - master
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Deploy
          command: |
            ssh -o StrictHostKeyChecking=no ubuntu@34.236.254.77 \
            "echo Start deploy && \
            cd ~/react-app/sonish-react-app && \
            git pull origin master && \
            cd .. && \
            sudo docker compose up --build -d && \
            echo Deploy end"
workflows:
  version: 2
  deploy_ec2:
    jobs:
      - build
